version: "3.9"

services:
  fake-certgen:
    image: nasenbaerchen/cmd/fake-certgen:fakecertgen
    container_name: fakecertgen
    ports:
      - 9000:9000

  dockerhubimage:
    image: nasenbaerchen/fakecertgen
    container_name: dockerhubimage
    ports:
      - 9001:9000
